version: 1
disable_existing_loggers: False

formatters:
  simpleFormatter:
    format: '%(levelname)s - %(message)s'
  fileFormatter:
    format: '[%(levelname) -10s] %(asctime)s  %(module) -15s:%(lineno)4s %(funcName)-20s %(message)s'
    datefmt: '%d/%m/%Y %H:%M:%S'
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simpleFormatter
    stream: ext://sys.stdout
  fileHandler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: fileFormatter
    filename: ./logconfig.log
    maxBytes: 1024
    backupCount: 3

loggers:
  root:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: no
  Tube4Droid:
    level: INFO
    handlers: [consoleHandler,fileHandler]
    qualname: Tube4Droid
    propagate: no
root:
  level: DEBUG
  handlers: [consoleHandler]
