name: MissingTvShowsForXBMC PR Build

permissions:
  contents: write
  packages: write
  issues: read
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: test with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        if: RUNNER_OS == "macOS"
      - name: Install prerequisites
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install mysql-client
          fi
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Install tox and pex dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pex tox tox-gh
        with:
          PKG_CONFIG_PATH: /opt/homebrew/opt/mysql-client/lib/pkgconfig
          MYSQLCLIENT_LDFLAGS: ${{pkg-config --libs mysqlclient}}
          MYSQLCLIENT_CFLAGS: ${{pkg-config --cflags mysqlclient}}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: tox 